### ISSUE TITLE
Sometimes when playing intro video I got: integer divide by zero

### ISSUE THREAD

**Issue by q4a** [opennox/opennox#470]
Sometimes after changing resolution and restarting game I got crash `integer divide by zero` when playing 2nd intro video.

System: Ubuntu 20.04 amd64
GPU: GT 730 + proprietary driver 470.103.01
Game builded from source on https://github.com/noxworld-dev/opennox/commit/c59eea01ab3a3618b279767c15e3c00376b08a81

Full log:
```
$ ./opennox-hd 
2022/04/10 15:41:58 [version]: version: v1.8.x (c59eea01)
2022/04/10 15:41:58 starting pprof server on "127.0.0.1:6060"
2022/04/10 15:41:58 [version]: GET https://ghcr.io/token?scope=repository%3Anoxworld-dev%2Fopennox%3Apull
2022/04/10 15:41:58 [config]: using file: "/home/q/game/nox/opennox.yml"
2022/04/10 15:41:58 [path]: setting data dir to: "/home/q/game/nox"
2022/04/10 15:41:58 [sdl]: window size: 640x480
2022/04/10 15:41:58 [sdl]: OpenGL version: 3.3.0 NVIDIA 470.103.01
2022/04/10 15:41:58 [render]: creating surface: 640x480
2022/04/10 15:41:58 [game]: game state code: Movies
2022/04/10 15:41:58 game flag set: Host | Client
2022/04/10 15:41:58 game flag set: Arena
2022/04/10 15:41:58 [version]: GET https://ghcr.io/v2/noxworld-dev/opennox/tags/list
2022/04/10 15:41:58 [sdl]: window size: 1920x1080
2022/04/10 15:41:58 [video]: gamma2: 1
2022/04/10 15:41:58 [gameex]: no config file
2022/04/10 15:41:58 [video]: mode switch: (640,480) (menu: true)
2022/04/10 15:41:58 [video]: initializing pixbuffer: (640,480)
2022/04/10 15:41:58 [input]: mouse bounds: (0,0)-(639,479)
2022/04/10 15:41:58 [video]: recreate render target: ok
2022/04/10 15:41:58 [version]: latest on github: v1.8.9
2022/04/10 15:41:59 [audio]: device ok
2022/04/10 15:41:59 [audio]: context ok
2022/04/10 15:41:59 [gui]: load: "MainBG.wnd"
2022/04/10 15:41:59 [gui]: load: "OptsBack.wnd"
2022/04/10 15:41:59 [game]: game state code: <none>
2022/04/10 15:41:59 [game]: movie found: "movies/WWLogo.vqa"
2022/04/10 15:41:59 [video]: DrawGeneralStart
2022/04/10 15:41:59 [video]: DrawGeneral: movie string: "movies/WWLogo.vqa"
2022/04/10 15:41:59 [render]: creating surface: 1920x1080
2022/04/10 15:41:59 [render]: recreating surface: 1920x1080 -> 640x400
2022/04/10 15:42:00 [game]: movie found: "movies/NoxLogo.vqa"
2022/04/10 15:42:00 [video]: DrawGeneralStart
2022/04/10 15:42:00 [video]: DrawGeneral: movie string: "movies/NoxLogo.vqa"
2022/04/10 15:42:00 [render]: creating surface: 1920x1080
2022/04/10 15:42:00 [render]: recreating surface: 1920x1080 -> 640x400
panic: runtime error: integer divide by zero

goroutine 68 [running]:
github.com/noxworld-dev/opennox/v1/client/noxmovie.(*MoviePlayer).Play.func1()
        /home/q/git/opennox/src/client/noxmovie/noxmovie.go:222 +0x475
created by github.com/noxworld-dev/opennox/v1/client/noxmovie.(*MoviePlayer).Play
        /home/q/git/opennox/src/client/noxmovie/noxmovie.go:209 +0x2c4
```

**Comment by Evengard** [comment]
This have to do smth with OpenAL audio buffers becoming invalid on dequeueing. Weird. Either will look into it or just migrate to oto or whatever.

**Comment by dennwc** [comment]
Should be fixed by 41fbe1718ef0fda0f1ac741aedf4783656708448.

**Comment by dennwc** [comment]
Still reproduces. Reopening.

**Comment by dennwc** [comment]
I think recent workaround finally fixed it.
