### ISSUE TITLE
Building from source tarball

### ISSUE THREAD

**Issue by fenuks** [opennox/opennox#495]
Building seems to depend on git, is there any way to build code tarball from release? I don't know golang, but from I understood, git repo is hard dependency for noxbuild/main.go

```sh
VERSION=1.8.10
cd /tmp
wget https://github.com/noxworld-dev/opennox/archive/refs/tags/v${VERSION}.tar.gz
tar xvf v${VERSION}.tar.gz
cd opennox-${VERSION}/src
LANG=en go run ./internal/noxbuild
```
results in
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
panic: exit status 128

goroutine 1 [running]:
github.com/noxworld-dev/opennox/v1/internal/vers/git.do({0xc0000eda80?, 0xc0000f2078?, 0xc0000edab8?})
        /tmp/opennox-1.8.10/src/internal/vers/git/git.go:21 +0x165
github.com/noxworld-dev/opennox/v1/internal/vers/git.ShortSHA(...)
        /tmp/opennox-1.8.10/src/internal/vers/git/git.go:51
github.com/noxworld-dev/opennox/v1/internal/vers/git.Version()
        /tmp/opennox-1.8.10/src/internal/vers/git/git.go:35 +0xa5
main.goBuild({0x5716dd, 0x7}, {0x5716dd?, 0xc0000d0299?}, 0xc0000ede48)
        /tmp/opennox-1.8.10/src/internal/noxbuild/main.go:109 +0x26e
main.buildTarget({0x5716dd?, 0xc000098568?})
        /tmp/opennox-1.8.10/src/internal/noxbuild/main.go:73 +0x105
main.build({0xc0000a8200?, 0xc0000a8200?, 0x401260?})
        /tmp/opennox-1.8.10/src/internal/noxbuild/main.go:54 +0x19e
main.main()
        /tmp/opennox-1.8.10/src/internal/noxbuild/main.go:40 +0x76
exit status 2
```

I'm running Linux.

**Comment by dennwc** [comment]
Yes, we'll fix that, thank you for reporting!

**Comment by coreybruce** [comment]
I am also getting exit status 1 and 2 but I am compiling the git source on Manjaro Arm64

**Comment by Evengard** [comment]
@coreybruce
First of all, logs pls!
Second, this is probably a separate issue.

**Comment by coreybruce** [comment]
Sure thing, I will also create a new issue report.
