### ISSUE TITLE
ALSA: cannot access file

### ISSUE THREAD

**Issue by hertzg** [opennox/opennox#501]
Tried with both stable and edge snap versions, same result. It seems to create the window and then crashes immediately.

```
hertz@potato:~$ opennox -data ~/Nox/
2022/06/24 03:06:46 [version]: version: v1.8.10 ()
2022/06/24 03:06:46 [version]: GET https://ghcr.io/token?scope=repository%3Anoxworld-dev%2Fopennox%3Apull
2022/06/24 03:06:46 [config]: using file: "/home/hertz/snap/opennox/common/opennox.yml"
2022/06/24 03:06:46 [path]: setting data dir to: "/home/hertz/Nox"
2022/06/24 03:06:46 [sdl]: window size: 640x480
2022/06/24 03:06:46 [sdl]: OpenGL version: 3.3.0 NVIDIA 510.73.05
2022/06/24 03:06:46 [render]: creating surface: 640x480
2022/06/24 03:06:46 [game]: game state code: Movies
2022/06/24 03:06:46 game flag set: Host | Client
2022/06/24 03:06:46 game flag set: Arena
2022/06/24 03:06:46 [version]: GET https://ghcr.io/v2/noxworld-dev/opennox/tags/list
2022/06/24 03:06:46 [version]: latest on github: v1.8.10
2022/06/24 03:06:46 [config]: reading legacy: "nox.cfg"
2022/06/24 03:06:46 [sdl]: window size: 1024x768
2022/06/24 03:06:46 [gameex]: no config file
2022/06/24 03:06:46 [video]: mode switch: (640,480) (menu: true)
2022/06/24 03:06:46 [video]: initializing pixbuffer: (640,480)
2022/06/24 03:06:46 [input]: mouse bounds: (0,0)-(639,479)
2022/06/24 03:06:46 [video]: recreate render target: ok
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2022/06/24 03:06:46 [audio]: device ok
2022/06/24 03:06:46 [audio]: context ok
2022/06/24 03:06:46 [audio]: error activating context: openal: invalid operation
2022/06/24 03:06:47 [gui]: load: "MainBG.wnd"
2022/06/24 03:06:47 [gui]: load: "OptsBack.wnd"
2022/06/24 03:06:47 [game]: game state code: <none>
2022/06/24 03:06:47 [game]: movie found: "movies/WWLogo.vqa"
2022/06/24 03:06:47 [video]: DrawGeneralStart
2022/06/24 03:06:47 [video]: DrawGeneral: movie string: "movies/WWLogo.vqa"
2022/06/24 03:06:47 [render]: creating surface: 1024x768
panic: zero handle [recovered]
	panic: zero handle

goroutine 1 [running, locked to thread]:
github.com/noxworld-dev/opennox/v1.RunArgs.func1()
	/root/parts/opennox/build/src/main.go:129 +0x98
panic({0x8ad9bc0, 0x8cf5e60})
	/snap/go/9760/src/runtime/panic.go:844 +0x223
github.com/noxworld-dev/opennox/v1/common/alloc/handles.AssertValid(...)
	/root/parts/opennox/build/src/common/alloc/handles/handles.go:60
github.com/noxworld-dev/opennox/v1/client/audio/ail.Driver.get(0x0)
	/root/parts/opennox/build/src/client/audio/ail/audio_openal.go:61 +0x112
github.com/noxworld-dev/opennox/v1/client/audio/ail.Driver.AllocateSample(0x0)
	/root/parts/opennox/build/src/client/audio/ail/audio_openal.go:621 +0x8b
github.com/noxworld-dev/opennox/v1/client/noxmovie.NewPlayerWithHandle({0x8cfab40, 0xbe64620}, {0x8cfd6f0, 0xb250240}, 0x0)
	/root/parts/opennox/build/src/client/noxmovie/noxmovie.go:85 +0xfb
github.com/noxworld-dev/opennox/v1.drawGeneral_4B0340(0x0)
	/root/parts/opennox/build/src/video_cgo.go:441 +0x370
github.com/noxworld-dev/opennox/v1.nox_game_rollLogoAndStart_4AB1F0()
	/root/parts/opennox/build/src/game.go:213 +0xfd
github.com/noxworld-dev/opennox/v1/client/gui.(*State).Switch(0x93c9210)
	/root/parts/opennox/build/src/client/gui/state.go:81 +0x5e
github.com/noxworld-dev/opennox/v1.nox_game_cdMaybeSwitchState_413800()
	/root/parts/opennox/build/src/gameloop.go:445 +0x42
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/root/parts/opennox/build/src/gameloop.go:292 +0x38c
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/root/parts/opennox/build/src/gameloop.go:519 +0x13d
github.com/noxworld-dev/opennox/v1.RunArgs({0xb024018, 0x3, 0x3})
	/root/parts/opennox/build/src/main.go:494 +0x2885
main.main()
	/root/parts/opennox/build/src/cmd/opennox/main.go:12 +0x3b
```

**Comment by Evengard** [comment]
Seems like it can't open the audio device.
The snap package is kinda broken, I'd recommend building manually after all.

**Comment by dennwc** [comment]
Looks like we might need to expose something else to Snap to make it properly connect to ALSA.

@hertzg What distro are you using?

**Comment by hertzg** [comment]
@dennwc Let me know if can help more

```
hertz@potato:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

```
hertz@potato:~$ uname -a
Linux potato 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hertzg** [comment]
Any news so far?

**Comment by dennwc** [comment]
I still need to reliably reproduce it on my system.

Otherwise #502 is also planned to at least keep running the game with no audio in these cases.

**Comment by hertzg** [comment]
> I still need to reliably reproduce it on my system.

Any way I could help reproduce it just let me know 🙏

**Comment by hydroEng** [comment]
Anyone know a workaround for this in the meantime?

**Comment by dennwc** [comment]
You try [Flatpak](https://flathub.org/apps/io.github.noxworld_dev.OpenNox) build (I assume this happens only on Snap build).

**Comment by PixelOfDeath** [comment]
Hello! I'm from the future!
For me the snap version has this issue (same error, no sound, intro video does not play without sound)
The flatpak version works fine for me!

Install (With flatkap already being installed on the system)
`flatpak install flathub io.github.noxworld_dev.OpenNox`

The files from the orignal game have to be put in the home folder in the folder "Nox".

Run
`flatpak run io.github.noxworld_dev.OpenNox`

or for the hd (higher resolution) version:
`flatpak run --command=opennox-hd io.github.noxworld_dev.OpenNox`
