### ISSUE TITLE
Game crash when launching spell "obliteration"

### ISSUE THREAD

**Issue by exebetche** [opennox/opennox#517]
platform: Linux Mint
version: 1.8.6
opennox-hd/Nox GOG 2.0.0.20

I've player many hours and everything works fine but when I try to cast the spell obliteration I got "panic: runtime error: index out of range". That occurs at the at end of the spell animation.

<details><summary>Console ouput</summary>
<p>

```2022/08/05 14:11:47 [nox] version: v1.8.6 ()
2022/08/05 14:11:47 [config]: using file: "/Games/Nox_gog/opennox.yml"
2022/08/05 14:11:47 [path]: setting data dir to: "/Games/Nox_gog"
2022/08/05 14:11:47 [sdl]: window size: 640x480
2022/08/05 14:11:47 [sdl]: OpenGL version: 3.3.0 NVIDIA 515.43.04
2022/08/05 14:11:47 [render]: creating surface: 640x480
2022/08/05 14:11:47 [game]: game state code: 10
2022/08/05 14:11:47 game flag set: Host | Flag2
2022/08/05 14:11:47 game flag set: Arena
2022/08/05 14:11:47 [sdl]: window size: 1920x1080
2022/08/05 14:11:47 [video]: gamma2: 0
2022/08/05 14:11:47 [gameex]: no config file
2022/08/05 14:11:47 [video]: mode switch: {W:640 H:480} (menu: true)
2022/08/05 14:11:47 [video]: initializing pixbuffer: {640 480}
2022/08/05 14:11:47 [input]: mouse bounds: (0,0)-(639,479)
2022/08/05 14:11:47 [video]: recreate render target: ok
2022/08/05 14:11:48 [audio]: device ok
2022/08/05 14:11:48 [audio]: context ok
2022/08/05 14:11:48 [gui]: load: "MainBG.wnd"
2022/08/05 14:11:48 [gui]: load: "OptsBack.wnd"
2022/08/05 14:11:48 [game]: game state code: -1
2022/08/05 14:11:48 [gui]: load: "legal.wnd"
2022/08/05 14:11:48 [audio]: MP3 stream: "dialog/c3mw225e.wav", 1 channels
2022/08/05 14:11:48 [audio]: ADPCM stream: "music/title.wav", 2 channels
2022/08/05 14:11:50 [game]: game state code: 100
2022/08/05 14:11:50 [gui]: load: "MainMenu.wnd"
2022/08/05 14:11:51 game flag set: Coop
2022/08/05 14:11:51 [audio]: ADPCM stream: "music/shell.wav", 2 channels
2022/08/05 14:11:52 [game]: game state code: 500
2022/08/05 14:11:52 [gui]: load: "SelChar.wnd"
2022/08/05 14:11:53 [game]: game state code: 100
2022/08/05 14:11:54 [game]: nox_xxx_servNewSession_4D1660
2022/08/05 14:11:54 [http]: http api server started: :18580
2022/08/05 14:11:54 [script]: player join: Player("Jack")
2022/08/05 14:11:54 [game]: play state: 2
2022/08/05 14:11:54 [script]: event: "MapExit"
2022/08/05 14:11:54 [script]: player leave: Player("Jack")
2022/08/05 14:11:54 game flag set: Flag20
2022/08/05 14:11:54 game flag unset: Flag20
2022/08/05 14:11:54 [game]: loading map "/Games/Nox_gog\\Save\\WORKING\\wiz11a\\wiz11a.map"
2022/08/05 14:11:54 [game]: checking map flags for "wiz11a"
2022/08/05 14:11:54 [game]: setting coop mode
2022/08/05 14:11:54 game flag unset: KOTR | CTF | FlagBall | Chat | Arena | Solo10 | Elimination | Quest
2022/08/05 14:11:54 game flag set: Solo10
2022/08/05 14:11:54 game flag set: Flag28
2022/08/05 14:11:54 game flag unset: Flag28
2022/08/05 14:11:54 game flag set: Pause
2022/08/05 14:11:54 game flag set: Flag18
2022/08/05 14:11:54 [video]: mode switch: {W:1280 H:720} (menu: false)
2022/08/05 14:11:54 [video]: initializing pixbuffer: {1280 720}
2022/08/05 14:11:54 [input]: mouse bounds: (0,0)-(1279,719)
2022/08/05 14:11:54 [video]: recreate render target: ok
2022/08/05 14:11:54 [gui]: load: "GUI_CTF.wnd"
2022/08/05 14:11:54 [gui]: load: "gui_fb.wnd"
2022/08/05 14:11:54 [gui]: load: "GuiFps.wnd"
2022/08/05 14:11:54 [gui]: load: "identify.wnd"
2022/08/05 14:11:54 [gui]: load: "Options.wnd"
2022/08/05 14:11:54 [gui]: load: "GuiKick.wnd"
2022/08/05 14:11:54 [gui]: load: "InputCfg.wnd"
2022/08/05 14:11:54 [gui]: load: "SelChar.wnd"
2022/08/05 14:11:54 [gui]: load: "Trade.wnd"
2022/08/05 14:11:54 [gui]: load: "Shop.wnd"
2022/08/05 14:11:54 [gui]: load: "GGOver.wnd"
2022/08/05 14:11:54 [gui]: load: "SKey.wnd"
2022/08/05 14:11:54 [gui]: load: "MultMove.wnd"
2022/08/05 14:11:54 [gui]: load: "Dialog.wnd"
2022/08/05 14:11:54 [gui]: load: "GuiChat.wnd"
2022/08/05 14:11:54 [gui]: load: "Briefing.wnd"
2022/08/05 14:11:54 [gui]: load: "yesno.wnd"
2022/08/05 14:11:54 [gui]: load: "motd.wnd"
2022/08/05 14:11:54 [gui]: load: "QuitMenu.wnd"
2022/08/05 14:11:54 [gui]: load: "discon.wnd"
2022/08/05 14:11:54 game flag set: Flag24
2022/08/05 14:11:54 [game]: play state: 3
2022/08/05 14:11:54 [video]: gamma: 0
2022/08/05 14:11:54 game flag set: Flag29
2022/08/05 14:11:54 game flag unset: Flag21 | Flag24
2022/08/05 14:11:54 [script]: event: "MapEntry"
2022/08/05 14:11:54 [lua]: loading script for map "wiz11a.map"
2022/08/05 14:11:54 [lua]: no lua script for map: "wiz11a.lua"
2022/08/05 14:11:54 [lua]: loaded module "Nox.Map.Script.v0"
2022/08/05 14:11:54 [script]: player join: Player("Jack")
2022/08/05 14:11:54 [render]: recreating surface: 640x480 -> 1280x720
2022/08/05 14:11:54 game flag unset: Pause
2022/08/05 14:11:55 [audio]: ADPCM stream: "music/town2.wav", 2 channels
panic: runtime error: index out of range [362] with length 47 [recovered]
	panic: runtime error: index out of range [362] with length 47

goroutine 1 [running, locked to thread]:
nox/v1.RunArgs.func1(0xa2cbf98)
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/main.go:122 +0x8d
panic({0x8948be0, 0xd5e9e70})
	/github/actions-runner/workspace/_tool/go/1.17.3/x64/src/runtime/panic.go:1052 +0x25b
nox/v1.nox_xxx_sprite_49AA00_drawable(0xbe649b30)
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/drawable.go:163 +0x301
nox/v1._Cfunc_sub_49BD70(0x8fd4b20)
	_cgo_gotypes.go:16519 +0x2f
nox/v1.nox_xxx_client_435F80_draw(0x9c7a080)
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/draw.go:766 +0x1fc
nox/v1.clientDraw()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/video_sdl.go:22 +0x23
nox/v1.mainloop_43E290()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/gameloop.go:257 +0x360
nox/v1.CONNECT_RESULT_OK()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/gameloop.go:906 +0x4bd
nox/v1.CONNECT_OR_HOST()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/gameloop.go:540 +0x6bf
nox/v1.mainloop_43E290()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/gameloop.go:348 +0xa50
nox/v1.cmainLoop()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/gameloop.go:469 +0x13f
nox/v1.RunArgs({0x9ca0108, 0x1, 0x1})
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/main.go:450 +0x2216
main.main()
	/github/actions-runner/workspace/nox-decomp/nox-decomp/src/cmd/opennox/main.go:12 +0x3b
(base) guix@guixpc:~$ sh /home/guix/.PlayOnLinux/wineprefix/Nox_gog/drive_c/GOG\ Games/Nox/launcher.sh
```

</p>
</details>

**Comment by dennwc** [comment]
Version v1.8.6 is very old, I think Obliteration was already fixed in v1.8.11, so I'm closing this. Please reopen if it reproduces with the latest release.
