### ISSUE TITLE
Wizard campaign is stuck after cutscene

### ISSUE THREAD

**Issue by Alexei-Kornienko** [opennox/opennox#577]
I play on Ubuntu 20.04 and in `wiz07e.map` after you step on the teleporter and cutscene begins game is stuck.
After Hecubah kills Horvath she is supposed to teleport you away but I have a black screen and map shows that I'm in the same room.

Sometimes this glitch is followed by a "Save Error" message sometimes it doesn't.
Additionally there is an error trace in the logs:

```
unexpected fault address 0xacacacac
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xacacacac pc=0x885e9a9]

goroutine 1 [running, locked to thread]:
runtime.throw({0x8bae7f2, 0x5})
	/snap/go/9848/src/runtime/panic.go:992 +0x6a fp=0x129eb3bc sp=0x129eb3a8 pc=0x8111a0a
runtime.sigpanic()
	/snap/go/9848/src/runtime/signal_unix.go:825 +0x1e7 fp=0x129eb3d4 sp=0x129eb3bc pc=0x8127df7
github.com/noxworld-dev/opennox/v1.(*Window).ID(...)
	/root/parts/opennox/build/src/gui_window.go:347
github.com/noxworld-dev/opennox/v1.(*Window).ChildByID(0xacacacac, 0xfa5)
	/root/parts/opennox/build/src/gui_window.go:443 +0x29 fp=0x129eb3e8 sp=0x129eb3d4 pc=0x885e9a9
github.com/noxworld-dev/opennox/v1.(*Window).ChildByID(0xb8c58b5c, 0xfa5)
	/root/parts/opennox/build/src/gui_window.go:447 +0x47 fp=0x129eb3fc sp=0x129eb3e8 pc=0x885e9c7
github.com/noxworld-dev/opennox/v1.sub449E00({0xb194cb0, 0xb})
	/root/parts/opennox/build/src/gui_dialog.go:139 +0x2f fp=0x129eb418 sp=0x129eb3fc pc=0x88498af
github.com/noxworld-dev/opennox/v1.NewDialogWindow(0xb8c54b60, {0xb194cb0, 0xb}, {0xb18d920, 0x29}, 0x38, 0x8bfdbcc, 0x0)
	/root/parts/opennox/build/src/gui_dialog.go:87 +0xcd fp=0x129eb44c sp=0x129eb418 pc=0x88492cd
github.com/noxworld-dev/opennox/v1.sub_4A1AA0(0xb8c54b60, {0x8d06320, 0xc9b3998})
	/root/parts/opennox/build/src/gui_main_menu.go:76 +0x244 fp=0x129eb478 sp=0x129eb44c pc=0x884b8d4
github.com/noxworld-dev/opennox/v1.(*Window).Func94(0xb8c54b60, {0x8d06320, 0xc9b3998})
	/root/parts/opennox/build/src/gui_window.go:561 +0xc8 fp=0x129eb498 sp=0x129eb478 pc=0x885f008
github.com/noxworld-dev/opennox/v1.nox_window_call_field_94_fnc(0xb8c54b60, 0x4007, 0xb8c551f0, 0x1c80189, 0x8d248f8, 0xab2)
	/root/parts/opennox/build/src/gui_window.go:180 +0x17c fp=0x129eb4ec sp=0x129eb498 pc=0x885df7c
_cgoexp_c45c40cb9095_nox_window_call_field_94_fnc(0xfff26870)
	_cgo_gotypes.go:21736 +0x46 fp=0x129eb50c sp=0x129eb4ec pc=0x88a6f06
runtime.cgocallbackg1(0x88a6ec0, 0xfff26870, 0x0)
	/snap/go/9848/src/runtime/cgocall.go:314 +0x22a fp=0x129eb568 sp=0x129eb50c pc=0x80dae1a
runtime.cgocallbackg(0x88a6ec0, 0xfff26870, 0x0)
	/snap/go/9848/src/runtime/cgocall.go:233 +0xda fp=0x129eb5a0 sp=0x129eb568 pc=0x80dab5a
runtime.cgocallback(0x80daa26, 0x88cab60, 0x129eb5e0)
	/snap/go/9848/src/runtime/asm_386.s:762 +0x80 fp=0x129eb5b0 sp=0x129eb5a0 pc=0x8142870
runtime.systemstack_switch()
	/snap/go/9848/src/runtime/asm_386.s:337 fp=0x129eb5b4 sp=0x129eb5b0 pc=0x81415a0
runtime.cgocall(0x88cab60, 0x129eb5e0)
	/snap/go/9848/src/runtime/cgocall.go:167 +0x86 fp=0x129eb5cc sp=0x129eb5b4 pc=0x80daa26
github.com/noxworld-dev/opennox/v1._Cfunc_nox_window_call_func_go(0x8939470, 0xb8c551f0, 0x7, 0x1c80189, 0x0)
	_cgo_gotypes.go:8849 +0x3b fp=0x129eb5e0 sp=0x129eb5cc pc=0x87ee6cb
github.com/noxworld-dev/opennox/v1.wrapWindowFuncC.func1.1(0x8939470, 0xb8c551f0, 0x7, 0x1c80189, 0x0)
	/root/parts/opennox/build/src/gui_window.go:64 +0x67 fp=0x129eb5fc sp=0x129eb5e0 pc=0x885d697
github.com/noxworld-dev/opennox/v1.wrapWindowFuncC.func1(0xb8c551f0, {0x8d063f8, 0x104cae20})
	/root/parts/opennox/build/src/gui_window.go:64 +0x74 fp=0x129eb620 sp=0x129eb5fc pc=0x885d5e4
github.com/noxworld-dev/opennox/v1.(*Window).Func93(0xb8c551f0, {0x8d063f8, 0x104cae20})
	/root/parts/opennox/build/src/gui_window.go:542 +0xc7 fp=0x129eb640 sp=0x129eb620 pc=0x885edb7
github.com/noxworld-dev/opennox/v1.nox_xxx_cursorUpdate_46B740(0xab05e00)
	/root/parts/opennox/build/src/input_c.go:656 +0x440 fp=0x129eb6e8 sp=0x129eb640 pc=0x88622c0
github.com/noxworld-dev/opennox/v1.processInput()
	/root/parts/opennox/build/src/seat_client.go:109 +0x3f fp=0x129eb6f4 sp=0x129eb6e8 pc=0x87e1d8f
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/root/parts/opennox/build/src/gameloop.go:290 +0x3bd fp=0x129eb788 sp=0x129eb6f4 pc=0x883c0ed
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/root/parts/opennox/build/src/gameloop.go:518 +0x13d fp=0x129eb7b4 sp=0x129eb788 pc=0x883d12d
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x1)
	/root/parts/opennox/build/src/gameloop.go:358 +0x697 fp=0x129eb848 sp=0x129eb7b4 pc=0x883c3c7
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/root/parts/opennox/build/src/gameloop.go:346 +0x6e4 fp=0x129eb8dc sp=0x129eb848 pc=0x883c414
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/root/parts/opennox/build/src/gameloop.go:518 +0x13d fp=0x129eb908 sp=0x129eb8dc pc=0x883d12d
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x1)
	/root/parts/opennox/build/src/gameloop.go:358 +0x697 fp=0x129eb99c sp=0x129eb908 pc=0x883c3c7
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/root/parts/opennox/build/src/gameloop.go:346 +0x6e4 fp=0x129eba30 sp=0x129eb99c pc=0x883c414
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/root/parts/opennox/build/src/gameloop.go:518 +0x13d fp=0x129eba5c sp=0x129eba30 pc=0x883d12d
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x1)
	/root/parts/opennox/build/src/gameloop.go:358 +0x697 fp=0x129ebaf0 sp=0x129eba5c pc=0x883c3c7
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/root/parts/opennox/build/src/gameloop.go:346 +0x6e4 fp=0x129ebb84 sp=0x129ebaf0 pc=0x883c414
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/root/parts/opennox/build/src/gameloop.go:518 +0x13d fp=0x129ebbb0 sp=0x129ebb84 pc=0x883d12d
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x1)
	/root/parts/opennox/build/src/gameloop.go:358 +0x697 fp=0x129ebc44 sp=0x129ebbb0 pc=0x883c3c7
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/root/parts/opennox/build/src/gameloop.go:346 +0x6e4 fp=0x129ebcd8 sp=0x129ebc44 pc=0x883c414
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/root/parts/opennox/build/src/gameloop.go:518 +0x13d fp=0x129ebd04 sp=0x129ebcd8 pc=0x883d12d
github.com/noxworld-dev/opennox/v1.RunArgs({0xa80e130, 0x1, 0x1})
	/root/parts/opennox/build/src/main.go:489 +0x27d1 fp=0x129ebf88 sp=0x129ebd04 pc=0x8866751
main.main()
	/root/parts/opennox/build/src/cmd/opennox/main.go:12 +0x3b fp=0x129ebfc4 sp=0x129ebf88 pc=0x88b48fb
runtime.main()
	/snap/go/9848/src/runtime/proc.go:250 +0x24d fp=0x129ebff0 sp=0x129ebfc4 pc=0x81145bd
runtime.goexit()
	/snap/go/9848/src/runtime/asm_386.s:1326 +0x1 fp=0x129ebff4 sp=0x129ebff0 pc=0x8142a71


```

**Comment by dennwc** [comment]
May be related to #503.

**Comment by dennwc** [comment]
Looks like it was fixed in the recent Alpha releases.
