### ISSUE TITLE
`panic: index out of range` in Village of Ix

### ISSUE THREAD

**Issue by al0fdf** [opennox/opennox#681]
When starting a solo conjurer campaign, I managed to create an autosave file that crashes after waiting for about 15 seconds.
Recount of game so far(if relevant):
* Get to village of Ix
* Buy apples and cider from shopkeeper located north in Village(top of screen as north)
* Get apple from small orchard in south of village
* Run through urchin den, skipping most of the chests
* Get to Aldwyn and buy charm creature spell from him
* Run through sewer/passage back to Ix
* Realise I don't have enough gold for poison spell, and go back to urchin den to raid some chests
* Buy poison book from Mystic(hooded shopkeeper)

The crash(reproduced with 727ad22ae):
```
2024/03/01 19:10:03 [audio]: ADPCM stream: "music/town1.wav", 2 channels
panic: runtime error: index out of range [253] with length 89 [recovered]
	panic: runtime error: index out of range [253] with length 89

goroutine 1 [running, locked to thread]:
github.com/noxworld-dev/opennox/v1.RunArgs.func1()
	/home/user/programs/nox/src/main.go:96 +0x9b
panic({0x8efbc60, 0xbe2d150})
	/usr/lib/go/src/runtime/panic.go:920 +0x24c
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.decodeNibble(0xe343, 0x0, 0xfd)
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:308 +0xbf
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.decodeADPCMStereo({0x11080000, 0x0, 0xc000}, {0xe6e3aa8, 0x400, 0xc000})
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:354 +0x1f0
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioStream).adpcmDecode(0xe6e2000, {0x11080000, 0xc000, 0xc000}, 0x2274)
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:483 +0x141
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioStream).decode(0xe6e2000, {0x11080000, 0xc000, 0xc000}, 0x2274)
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:405 +0x8f
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioStream).work(0xe6e2000)
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:1436 +0x22a
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioDriver).doWork(0xb21a120)
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:1479 +0xa0
github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.Serve()
	/home/user/programs/nox/src/legacy/client/audio/ail/audio_openal.go:1060 +0x138
github.com/noxworld-dev/opennox/v1.(*Client).sub4312C0(0xb3f0000)
	/home/user/programs/nox/src/client.go:170 +0x2c
github.com/noxworld-dev/opennox/v1.(*Client).Update(0xb3f0000)
	/home/user/programs/nox/src/client.go:158 +0x237
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x1)
	/home/user/programs/nox/src/gameloop.go:161 +0x543
github.com/noxworld-dev/opennox/v1.mainloop_43E290(0x0)
	/home/user/programs/nox/src/gameloop.go:186 +0x743
github.com/noxworld-dev/opennox/v1.cmainLoop()
	/home/user/programs/nox/src/gameloop.go:354 +0x13e
github.com/noxworld-dev/opennox/v1.RunArgs({0xa93c018, 0x3, 0x3})
	/home/user/programs/nox/src/main.go:461 +0x2c17
main.main()
	cmd/opennox/main.go:12 +0x3b
```

The autosave:
[IX_CONJURER_AUTOSAVE_BROKEN.zip](https://github.com/noxworld-dev/opennox/files/14458651/IX_CONJURER_AUTOSAVE_BROKEN.zip)

This was done while I was trying to fix https://github.com/noxworld-dev/opennox/issues/301, so the autosave was not made by a clean build of the engine.

**Comment by dennwc** [comment]
Not sure why it finds a bad audio stream, but it definitely shouldn't crash the engine. Will fix that.

**Comment by angrykirc** [comment]
Did not crash the game for me @ 48ebb887, maybe you have something wrong with the game files?
Anyways, agree that it shouldn't crash the game

**Comment by al0fdf** [comment]
Stack trace:

```
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1217 (hits goroutine(1):1 total:1) (PC: 0x80a02b0)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "runtime error: index out of range [253] with length 89"
  1212:	// fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
  1213:	// that if msgs != nil, fatalpanic also prints panic messages and decrements
  1214:	// runningPanicDefers once main is blocked from exiting.
  1215:	//
  1216:	//go:nosplit
=>1217:	func fatalpanic(msgs *_panic) {
  1218:		pc := getcallerpc()
  1219:		sp := getcallersp()
  1220:		gp := getg()
  1221:		var docrash bool
  1222:		// Switch to the system stack to avoid any stack growth, which
(dlv) stack
 0  0x00000000080a02b0 in runtime.fatalpanic
    at /usr/lib/go/src/runtime/panic.go:1217
 1  0x000000000809f420 in runtime.gopanic
    at /usr/lib/go/src/runtime/panic.go:779
 2  0x0000000008ba911f in github.com/noxworld-dev/opennox/v1.RunArgs.func1
    at ./main.go:96
 3  0x000000000809f3f3 in runtime.gopanic
    at /usr/lib/go/src/runtime/panic.go:770
 4  0x000000000809de56 in runtime.goPanicIndex
    at /usr/lib/go/src/runtime/panic.go:114
 5  0x000000000856762f in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.decodeNibble
    at ./legacy/client/audio/ail/audio_openal.go:308
 6  0x0000000008567ae0 in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.decodeADPCMStereo
    at ./legacy/client/audio/ail/audio_openal.go:354
 7  0x00000000085682b1 in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioStream).adpcmDecode
    at ./legacy/client/audio/ail/audio_openal.go:483
 8  0x0000000008567f8f in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioStream).decode
    at ./legacy/client/audio/ail/audio_openal.go:405
 9  0x000000000856e70a in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioStream).work
    at ./legacy/client/audio/ail/audio_openal.go:1436
10  0x000000000856e8b0 in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.(*audioDriver).doWork
    at ./legacy/client/audio/ail/audio_openal.go:1479
11  0x000000000856bfe1 in github.com/noxworld-dev/opennox/v1/legacy/client/audio/ail.Serve
    at ./legacy/client/audio/ail/audio_openal.go:1060
12  0x0000000008b3a65c in github.com/noxworld-dev/opennox/v1.(*Client).sub4312C0
    at ./client.go:170
13  0x0000000008b3a4e7 in github.com/noxworld-dev/opennox/v1.(*Client).Update
    at ./client.go:158
14  0x0000000008b81b46 in github.com/noxworld-dev/opennox/v1.mainloop_43E290
    at ./gameloop.go:161
15  0x0000000008b81d29 in github.com/noxworld-dev/opennox/v1.mainloop_43E290
    at ./gameloop.go:186
16  0x0000000008b82d4e in github.com/noxworld-dev/opennox/v1.cmainLoop
    at ./gameloop.go:354
17  0x0000000008ba8a9c in github.com/noxworld-dev/opennox/v1.RunArgs
    at ./main.go:461
18  0x0000000008c563fb in main.main
    at cmd/opennox/main.go:12
19  0x00000000080a2d76 in runtime.main
    at /usr/lib/go/src/runtime/proc.go:271
20  0x00000000080db221 in runtime.goexit
    at /usr/lib/go/src/runtime/asm_386.s:1363
```

**Comment by al0fdf** [comment]
The files TOWN1.wav, TOWN3.wav, WANDER2.wav and SHELL.wav showed `data` when `file` was run on them, they did not play with any music players, and were silent in-game. When copying 'good' wav files to the music folder, the game no longer crashes. However, when copying the 'bad' files back to the music folder, I can no longer reproduce the bug.
